### ISSUE TITLE
客户端发布消息是报错

### ISSUE THREAD

**Issue by koiding** [xavier-chen/swoole_mqtt_php#1]
PHP Fatal error:  Uncaught Error: Call to undefined method Server::redis_get() in /root/swoole_mqtt_php/swoole_server.php:88
Stack trace:
#0 /root/swoole_mqtt_php/swoole_server.php(46): Server->decode_mqtt('0\x06\x00\x04asdf', Object(swoole_server), 2)
#1 [internal function]: Server->onReceive(Object(swoole_server), 2, 0, '0\x06\x00\x04asdf')
#2 /root/swoole_mqtt_php/swoole_server.php(22): swoole_server->start()
#3 /root/swoole_mqtt_php/swoole_server.php(223): Server->__construct()
#4 {main}
  thrown in /root/swoole_mqtt_php/swoole_server.php on line 88
[2016-11-22 17:53:05 *14288.0]	ERROR	zm_deactivate_swoole (ERROR 103): Fatal error: Uncaught Error: Call to undefined method Server::redis_get() in /root/swoole_mqtt_php/swoole_server.php:88
Stack trace:
#0 /root/swoole_mqtt_php/swoole_server.php(46): Server->decode_mqtt('0\x06\x00\x04asdf', Object(swoole_server), 2)
#1 [internal function]: Server->onReceive(Object(swoole_server), 2, 0, '0\x06\x00\x04asdf')
#2 /root/swoole_mqtt_php/swoole_server.php(22): swoole_server->start()
#3 /root/swoole_mqtt_php/swoole_server.php(223): Server->__constru
[2016-11-22 17:53:05 $14271.0]	WARNING	swManager_check_exit_status: worker#0 abnormal exit, status=255, signal=0

和redis有关的函数要另外装扩展吗

**Comment by xavier-chen** [comment]
redis这个可以忽略，是我自己的项目中的封装函数，你仔细看代码，就知道如何进行了。好久没有更新的项目，回头更新一下，把完整的mqtt放出来

**Comment by dawnmn** [comment]
这个用swoole实现mqtt，感觉很不错，什么时候能够完成mqtt的主体功能呢

**Comment by zerovszero** [comment]
请问您什么时候把mqtt整体放出来？
